apiVersion: v1
kind: Service
metadata:
  name: devcon-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: devcon-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000