apiVersion: apps/v1
kind: Deployment
metadata:
  name: devcon-service
  labels:
    app: DevconService
    app.kubernetes.io/name: devcon-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devcon-service
      app.kubernetes.io/name: devcon-service
  template:
    metadata:
      labels:
        app: devcon-service
        app.kubernetes.io/name: devcon-service
    spec:
      containers:
      - name: devcon-service
        image: mjjos1/devcon-service:0.9.8
        ports:
        - containerPort: 3000
